webapp/kortkatalogen/base/urls.py
from django.conf.urls import url
from base import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

webapp/kortkatalogen/kortkatalogen/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ullas/', include('ullas.urls', namespace="ullas")),
    url(r'^hsnominal/', include('hsnominal.urls', namespace="hsnominal")),
    url(r'^$', include('base.urls')),
]

admin.site.site_header = 'Kortkatalogen admin'

webapp/kortkatalogen/ullas/urls.py
from django.conf.urls import url, include
from ullas import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<card_catalog_sequence_number>[0-9]+)/$', views.browse, name='cardurl'),
]

webapp/kortkatalogen/ullas/models.py
from django.db import models
from base.models import *
from appconf import AppConf
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from djorm_pgfulltext.models import SearchManager
from djorm_pgfulltext.fields import VectorField

class Box(BaseBox):
    pass


class Card(BaseCard):
    box = models.ForeignKey(Box, related_name="cards", verbose_name="kort")
    search_index = VectorField()
    objects = SearchManager(
        fields = ('name', 'ocr_text', 'ocr_text_back'),
        config = 'pg_catalog.swedish',
        search_field = 'search_index',
        auto_update_search_field = True
    )

    # readonly field to show preview pic in django admin interface
    def image_tag(self):
        return """<img style="width:450px" alt="Kort %s" src="/carddata/%s/%s" />""" % (self.catalog_sequence_number, settings.ULLAS_CARDS_SUBFOLDER, self.box.folder_name + "/" + self.filename)

    def image_tag_back(self):
        if self.filename_back:
            return """<img style="width:450px" alt="Baksida kort %s" src="/carddata/%s/%s" />""" % (self.catalog_sequence_number, settings.ULLAS_CARDS_SUBFOLDER, self.box.folder_name + "/" + self.filename_back)
        else:
            return None

    image_tag.short_description = 'Bild'
    image_tag.allow_tags = True
    image_tag_back.short_description = 'Bild'
    image_tag_back.allow_tags = True




# App specific conf (see http://django-appconf.readthedocs.io/en/latest/)
class UllasConf(AppConf):
    CARDS_SUBFOLDER = "ullas"

webapp/kortkatalogen/ullas/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from ullas.models import *
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):

    # Read alphabet index cards
    index_cards = Card.objects.filter(letter__isnull=False).exclude(letter='').order_by("letter")

    # Read boxes
    return render_to_response('ullas/index.html', locals())


def search(request):
    if request.GET.get("q"):
        query = request.GET.get("q", None)
        result = Card.objects.search(query)[:100]
        paginator = Paginator(result, 20)

        pageno = request.GET.get('page')

        try:
            page = paginator.page(pageno)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            page = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            page = paginator.page(paginator.num_pages)

    return render_to_response('ullas/search.html', locals())


def browse(request, card_catalog_sequence_number):
    card = Card.objects.get(catalog_sequence_number=card_catalog_sequence_number)
    box = card.box
    box_cards = box.cards.all().only("catalog_sequence_number", "name") #for right column list display
    image_url = box.folder_name + "/" + card.filename
    fullres_image_url = box.folder_name + "/" + card.filename
    image_back_url = box.folder_name + "/" + card.filename_back
    fullres_image_back_url = box.folder_name + "/" + card.filename_back

    # find next and previous card
    try:
        previous_card = Card.objects.get(catalog_sequence_number=card.catalog_sequence_number - 1)
    except Card.DoesNotExist:
        previous_card = None

    try:
        next_card = Card.objects.get(catalog_sequence_number=card.catalog_sequence_number + 1)
    except Card.DoesNotExist:
        next_card = None

    # find +10 and -10 cards
    try:
        previous10_card = Card.objects.get(catalog_sequence_number=card.catalog_sequence_number - 10)
    except Card.DoesNotExist:
        previous10_card = None

    try:
        next10_card = Card.objects.get(catalog_sequence_number=card.catalog_sequence_number + 10)
    except Card.DoesNotExist:
        next10_card = None


    # next and previous box
    try:
        previous_box_card = Card.objects.filter(box__sequence_number = box.sequence_number - 1)[0]
    except:
        previous_box_card = None

    try:
        next_box_card = Card.objects.filter(box__sequence_number = box.sequence_number + 1)[0]
    except:
        next_box_card = None

    return render_to_response('ullas/browse.html', locals())

webapp/kortkatalogen/ullas/templates/ullas/_navbar.html
{% load staticfiles %}
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand navbar-logo" href="/"><img src="{% static 'img/kb_logo_white.svg' %}" alt="Till startsidan"/></a>
          <a class="navbar-brand" href="/ullas/">Ullas kortkatalog</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/ullas/om/">Om katalogen</a></li>
            </ul>
        </div>
      </div>
    </nav>

webapp/kortkatalogen/ullas/templates/ullas/_paginator.html
<div class="row text-center">
  <nav>
    <ul class="pagination pagination-lg">

      <li>
        {% if previous_box_card %}
        <a href="{% url "ullas:cardurl" previous_box_card.catalog_sequence_number %}">Föreg. låda</a>
        {% else %}
        <a href="#" class="disabled">Föreg. låda</a>
        {% endif %}
      </li>

      <li>
        {% if previous10_card %}
        <a href="{% url "ullas:cardurl" previous10_card.catalog_sequence_number %}">-10</a>
        {% else %}
        <a href="#" class="disabled">-10</a>
        {% endif %}
      </li>
      <li class="pagination-previous">
        {% if previous_card %}
        <a property="xhv:previous" href="{% url "ullas:cardurl" previous_card.catalog_sequence_number %}"><span aria-hidden="true">&laquo;</span></a>
        {% else %}
        <a href="#" class="disabled"><span aria-hidden="true">&laquo;</span></a>
        {% endif %}
      </li>
      <li class="pagination-next">
        {% if next_card %}
        <a property="xhv:next" href="{% url "ullas:cardurl"  next_card.catalog_sequence_number %}"><span aria-hidden="true">&raquo;</span></a>
        {% else %}
        <a href="#" class="disabled"><span aria-hidden="true">&raquo;</span></a>
        {% endif %}
      </li>

      <li>
        {% if next10_card %}
        <a href="{% url "ullas:cardurl" next10_card.catalog_sequence_number %}">+10</a>
        {% else %}
        <a href="#" class="disabled">+10</span></a>
        {% endif %}
      </li>
      <li>

        {% if next_box_card %}
        <a href="{% url "ullas:cardurl"  next_box_card.catalog_sequence_number %}">Nästa låda</a>
        {% else %}
        <a href="#" class="disabled">Nästa låda</span></a>
        {% endif %}
      </li>
    </ul>
  </nav>
</div>

webapp/kortkatalogen/ullas/templates/ullas/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}
Om Ullas tidningskatalog
{% endblock %}

{% block navbar %}
{% include "ullas/_navbar.html" %}
{% endblock %}
{% block content %}

    <div class="container" role="main">
      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header">Om Ullas tidningskatalog</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <p>(text)</p>

          <h2>Innehåll</h2>
          <p>(text)</p>
          <p>På sidan för ett kort kan du klicka på bilden för att se den i full upplösning.</p>

          <h2>Frågor om katalogen?</h2>
          <p>(text)</p>

          <h2>Innehållet är fritt att återanvända</h2>
          <p>Bildfiler och texter i katalogen är fria att återanvända enligt <span lang="en">Creative Commons</span> <a rel="license" href="http://creativecommons.org/publicdomain/zero/1.0/">CC0</a>.</p>
        </div>

        <div class="col-md-4">
          <p>Exempel</p>
        </div>
      </div>
    </div>
{% endblock %}

webapp/kortkatalogen/ullas/templates/ullas/browse.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}
#{{card.catalog_sequence_number}} {{card.name}}
{% endblock %}

{% block head_opengraph %}
<meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:title" content="Kort {{card.catalog_sequence_number}}: {{card.name}}" />
    <meta property="og:description" content="{{card.name}} Katalogkort {{card.catalog_sequence_number}}." />
    <meta property="og:image" content="/carddata/ullas/{{fullres_image_url}}" />
{% endblock %}

{% block navbar %}
{% include "ullas/_navbar.html" %}
{% endblock %}
{% block content %}

    <div class="container card" role="main" resource="" vocab="http://schema.org/" prefix="xhv:http://www.w3.org/1999/xhtml/vocab#" typeof="ItemPage">
      <meta property="isPartOf" href="https://kortkataloger.kb.se/ullas/" />
      {% include "ullas/_paginator.html" %}

      <div class="row">
        <div class="col-md-12">
          <h1 class="page-header" property="name">Kort #{{card.catalog_sequence_number}} <span>{{card.name}}</span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6" property="associatedMedia" typeof="ImageObject">
          <meta property="isFamilyFriendly" content="true" />
          <meta property="representativeOfPage" content="true" />
          <meta property="inLanguage" href="http://lexvo.org/id/iso639-3/swe" />
          <meta property="license" href="http://creativecommons.org/publicdomain/mark/1.0/" />
          <a property="contentUrl" href="/carddata/ullas/{{fullres_image_url}}"><img property="embedUrl" class="preview" src="/carddata/ullas/{{image_url}}"  alt="{{card.name}} {{card.ocr_text}}"></a>
          <a property="contentUrl" href="/carddata/ullas/{{fullres_image_back_url}}"><img property="embedUrl" class="preview" src="/carddata/ullas/{{image_back_url}}"  alt="Baksida {{card.name}} {{card.ocr_text_back}}"></a>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Information</h3>
                </div>
                <div class="panel-body">
          <dl>

          <dt class="cardno">Kortnr:</dt>
          <dd>{{card.catalog_sequence_number}}</dd>
          <dt class="boxno">Låda:</dt>
          <dd>{{card.box.sequence_number}} {{card.box.label}}</dd>


          {% if card.ocr_text %}
          <dt>OCR-text:</dt>
          <dd class="ocr">{{card.ocr_text|linebreaks}}</dd>
          {% endif %}

          </dl>
                  </div>
            </div>

          {% if card.ocr_text %}
          <div class="panel panel-warning">
            <div class="panel-heading">
              Konstig text ovan?
            </div>
            <div class="panel-body">
              <p>Den automatiska konverteringen kan ha skapat felaktiga tecken.</p>
            </div>
          </div>
          {% endif %}

          <p><a class="btn btn-primary btn-block question" onclick="javascript:_paq.push(['trackGoal', 1]);" href="mailto:Kungl.bib@kb.se?subject=Fråga om kort {{card.catalog_sequence_number|urlencode}} ({{card.name|urlencode}}) i Ullas katalog&amp;body=%0D%0A%0D%0A%0D%0A%0D%0ANamn: {{card.name|urlencode}}%0D%0AKortlänk: {{request.build_absolute_uri|urlencode}}" role="button">Fråga om detta kort</a></p>
        </div>
        <div class="col-md-3" role="complementary">
          <h2>Låda {{card.box.sequence_number}} {{card.box.label}}</h2>
          <ul class="list-unstyled box">
            {% for c in box_cards %}
              <li>
              {% ifequal c.catalog_sequence_number card.catalog_sequence_number %}
              <a href="{% url "ullas:cardurl" c.catalog_sequence_number %}" class="selected">#{{c.catalog_sequence_number}}</a>
              {% else %}
              <a href="{% url "ullas:cardurl" c.catalog_sequence_number %}">{{c.catalog_sequence_number}}</a>
              {% endifequal %}
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>

      {% include "ullas/_paginator.html" %}
    </div>

{% endblock %}

webapp/kortkatalogen/ullas/templates/ullas/index.html
{% extends "base.html" %}
{% block head_opengraph %}
<meta property="og:url" content="https://kortkataloger.kb.se/ullas/" />
<meta property="og:title" content="Ullas tidningskatalog - Kungliga biblioteket" />
<meta property="og:description" content="Digitaliserad version av Ullas tidningskatalog på Kungliga biblioteket." />
<meta property="og:image" content="https://kortkataloger.kb.se/static/img/0092_alfa_20140708_0027_beskuren.jpg" />
{% endblock %}
{% block navbar %}
{% include "ullas/_navbar.html" %}
{% endblock %}

{% block content %}

<div class="jumbotron bg-happy-muted-light-blue">
  <div class="container">
    <h1 class="text-small text-black calltoaction">Sök i Ullas tidningskatalog</h1>
    <form class="form-horizontal" method="get" action="/ullas/search/" role="search">
      <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-4">
          <label class="sr-only" for="q">Sök efter</label>
          <input type="search" id="q" name="q" class="form-control">
        </div>
        <div class="col-md-2 col-xs-12">
          <button type="submit" id="searchbtn" class="btn-block btn btn-primary">Sök</button>
        </div>
        <div class="col-md-3"></div>
      </div>
    </form>
    <div class="col-md-12 col-xs-12"><a href="#alfa" class="text-black">&hellip;eller bläddra via alfabetiskt index.</a></div>
  </div>
</div>

    <div class="container" role="main" vocab="http://schema.org/" resource="" typeof="CollectionPage">
      <div class="row">
        <div class="col-md-6">
          <h1>Om Ullas tidningskatalog</h1>
          <meta property="name" content="Om Ullas tidningskatalog" />
          <meta property="mainEntityOfPage" href="http://libris.kb.se/bib/16922704" />
          <meta property="hasPart" content="/alfa/1/" />
          <meta property="publisher" href="http://id.kb.se/resource/auth/121848" />

          <div property="description">
            <p>(beskrivningstext)</p>
          </div>

        </div>
        <div class="col-md-6 teaser">
          <p><a href="">(exempelkort)</a></p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h2 id="alfa">Alfabetiskt index</h2>
          <p>Utgå från det alfabetiska indexet genom att välja en bokstav nedan.</p>
          <ul class="pagination pagination-sm">
            {% for card in index_cards %}
            <li>
            <a href="{% url "ullas:cardurl" card.catalog_sequence_number %}">{{card.letter}}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
{% endblock %}

webapp/kortkatalogen/ullas/templates/ullas/search.html
{% extends "base.html" %}
{% load bootstrap_pagination %}

{% block head_title %}
Sök i Ullas tidningskatalog
{% endblock %}

{% block navbar %}
{% include "ullas/_navbar.html" %}
{% endblock %}
{% block content %}

<div class="container contentpage" role="main">
  <div class="row">
    <div class="col-md-12">
      <h1>Sök i katalogen</h1>
      <p>Observera att sökningen sker i det automattolkade textunderlaget. Handskriven text går inte att söka i.</p>
      <form class="form-horizontal global-search" action="/ullas/search/" role="search">
        <div class="col-md-6">
          <label class="sr-only" for="q">Sök efter</label>
          <input type="search" class="form-control" id="q" name="q" value="{{query}}">
        </div>
        <div class="col-md-2 col-xs-12">
          <button type="submit" id="searchbtn" class="btn-block btn btn-primary">Sök</button>
        </div>
      </form>
    </div>
  </div>

  <div class="row searchresult">
    <div class="col-md-12">
      {% if searcherror %}
      <div class="alert alert-danger" role="alert">
        <strong>Sökfunktionen fungerar inte just nu</strong>
        <p>Ett fel förhindrar sökfunktionen från att fungera. Var vänlig försök senare.</p>
      </div>
      {% endif %}

      {% if page %}
        <h2 id="result">Sökresultat</h2>
        <p>{{ page.paginator.count }} träffar.</p>
        {% bootstrap_paginate page range=20 show_prev_next="true" show_first_last="true" %}

        {% for result in page.object_list %}

        <div class="row result">
          <div class="col-md-8">
            <h3><a href="{% url "ullas:cardurl" result.catalog_sequence_number %}">Kort {{result.catalog_sequence_number}}</a></h3>
            <p>{{ result.ocr_text }}</p>
          </div>
          <div class="col-md-4">
          </div>
        </div>
        {% endfor %}

        {% bootstrap_paginate page range=20 %}

      {% else %}
        {% if query %}
          <div class="alert alert-warning" role="alert">
            <strong>Inga kort hittades för det angivna sökbegreppet</strong>
            <p>Textunderlaget är automatiskt tolkat från vissa av korten och sökningen sker därför inte över alla kort.</p>
          </div>
        {% endif %}
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}